categories = [
    "Animals", "Cities", "Countries", "Famous People", "Food", "Movies", 
    "Occupations", "Sports", "Historical Events", "Books", "Instruments", 
    "Plants", "Toys", "Brands", "Celebrities", "Rivers", "Mountains", 
    "Historical Figures", "TV Shows", "Musical Instruments",
    "Actors", "Colors", "Countries", "Diseases", "School Subjects",
    "Video Games", "Authors", "Board Games", "Car Brands", "Fruits",
    "Vegetables", "Scientists", "Sports Personalities", "Computer Parts", 
    "Languages", "Beaches", "Historical Monuments", "Musical Genres", "Dance Styles", 
    "Mythical Creatures",
    "Astronomical Objects", "Chemical Elements", "Mathematical Concepts", "Philosophers", "Painters",
    "Literary Genres", "Poets", "Festivals", "Religions", "Political Ideologies",
    "Mammals", "Birds", "Fish", "Reptiles", "Amphibians",
    "Trees", "Flowers", "Herbs", "Spices", "Cooking Utensils",
    "Kitchen Appliances", "Furniture", "Architectural Styles", "World Leaders", "Historical Battles",
    "Wars", "Sports Equipment", "Olympic Sports", "Card Games", "Puzzles",
    "Programming Languages", "Operating Systems", "Tech Companies", "Inventions", "Natural Disasters",
    "Weather Phenomena", "Sea Creatures", "Mountain Ranges", "Deserts", "Islands",
    "National Parks", "Dog Breeds", "Cat Breeds", "Horse Breeds", "Bird Species"
]

# Translations
translations = {
    "English": {
        "Animals": "Animals",
        "Cities": "Cities",
        "Countries": "Countries",
        "Famous People": "Famous People",
        "Food": "Food",
        "Movies": "Movies",
        "Occupations": "Occupations",
        "Sports": "Sports",
        "Historical Events": "Historical Events",
        "Books": "Books",
        "Instruments": "Instruments",
        "Plants": "Plants",
        "Toys": "Toys",
        "Brands": "Brands",
        "Celebrities": "Celebrities",
        "Rivers": "Rivers",
        "Mountains": "Mountains",
        "Historical Figures": "Historical Figures",
        "TV Shows": "TV Shows",
        "Musical Instruments": "Musical Instruments",
        "Actors": "Actors",
        "Colors": "Colors",
        "Diseases": "Diseases",
        "School Subjects": "School Subjects",
        "Video Games": "Video Games",
        "Authors": "Authors",
        "Board Games": "Board Games",
        "Car Brands": "Car Brands",
        "Fruits": "Fruits",
        "Vegetables": "Vegetables",
        "Scientists": "Scientists",
        "Sports Personalities": "Sports Personalities",
        "Computer Parts": "Computer Parts",
        "Languages": "Languages",
        "Beaches": "Beaches",
        "Historical Monuments": "Historical Monuments",
        "Musical Genres": "Musical Genres",
        "Dance Styles": "Dance Styles",
        "Mythical Creatures": "Mythical Creatures",
        "Astronomical Objects": "Astronomical Objects",
        "Chemical Elements": "Chemical Elements",
        "Mathematical Concepts": "Mathematical Concepts",
        "Philosophers": "Philosophers",
        "Painters": "Painters",
        "Literary Genres": "Literary Genres",
        "Poets": "Poets",
        "Festivals": "Festivals",
        "Religions": "Religions",
        "Political Ideologies": "Political Ideologies",
        "Mammals": "Mammals",
        "Birds": "Birds",
        "Fish": "Fish",
        "Reptiles": "Reptiles",
        "Amphibians": "Amphibians",
        "Trees": "Trees",
        "Flowers": "Flowers",
        "Herbs": "Herbs",
        "Spices": "Spices",
        "Cooking Utensils": "Cooking Utensils",
        "Kitchen Appliances": "Kitchen Appliances",
        "Furniture": "Furniture",
        "Architectural Styles": "Architectural Styles",
        "World Leaders": "World Leaders",
        "Historical Battles": "Historical Battles",
        "Wars": "Wars",
        "Sports Equipment": "Sports Equipment",
        "Olympic Sports": "Olympic Sports",
        "Card Games": "Card Games",
        "Puzzles": "Puzzles",
        "Programming Languages": "Programming Languages",
        "Operating Systems": "Operating Systems",
        "Tech Companies": "Tech Companies",
        "Inventions": "Inventions",
        "Natural Disasters": "Natural Disasters",
        "Weather Phenomena": "Weather Phenomena",
        "Sea Creatures": "Sea Creatures",
        "Mountain Ranges": "Mountain Ranges",
        "Deserts": "Deserts",
        "Islands": "Islands",
        "National Parks": "National Parks",
        "Dog Breeds": "Dog Breeds",
        "Cat Breeds": "Cat Breeds",
        "Horse Breeds": "Horse Breeds",
        "Bird Species": "Bird Species"
    },
    "German": {
        "Animals": "Tiere",
        "Cities": "Städte",
        "Countries": "Länder",
        "Famous People": "Berühmte Personen",
        "Food": "Lebensmittel",
        "Movies": "Filme",
        "Occupations": "Berufe",
        "Sports": "Sportarten",
        "Historical Events": "Historische Ereignisse",
        "Books": "Bücher",
        "Instruments": "Instrumente",
        "Plants": "Pflanzen",
        "Toys": "Spielzeuge",
        "Brands": "Marken",
        "Celebrities": "Prominente",
        "Rivers": "Flüsse",
        "Mountains": "Berge",
        "Historical Figures": "Historische Figuren",
        "TV Shows": "Fernsehshows",
        "Musical Instruments": "Musikinstrumente",
        "Actors": "Schauspieler",
        "Colors": "Farben",
        "Diseases": "Krankheiten",
        "School Subjects": "Schulfächer",
        "Video Games": "Videospiele",
        "Authors": "Autoren",
        "Board Games": "Brettspiele",
        "Car Brands": "Automarken",
        "Fruits": "Früchte",
        "Vegetables": "Gemüse",
        "Scientists": "Wissenschaftler",
        "Sports Personalities": "Sportpersönlichkeiten",
        "Computer Parts": "Computerteile",
        "Languages": "Sprachen",
        "Beaches": "Strände",
        "Historical Monuments": "Historische Denkmäler",
        "Musical Genres": "Musikgenres",
        "Dance Styles": "Tanzstile",
        "Mythical Creatures": "Mythische Kreaturen",
        "Astronomical Objects": "Astronomische Objekte",
        "Chemical Elements": "Chemische Elemente",
        "Mathematical Concepts": "Mathematische Konzepte",
        "Philosophers": "Philosophen",
        "Painters": "Maler",
        "Literary Genres": "Literarische Genres",
        "Poets": "Dichter",
        "Festivals": "Festivals",
        "Religions": "Religionen",
        "Political Ideologies": "Politische Ideologien",
        "Mammals": "Säugetiere",
        "Birds": "Vögel",
        "Fish": "Fische",
        "Reptiles": "Reptilien",
        "Amphibians": "Amphibien",
        "Trees": "Bäume",
        "Flowers": "Blumen",
        "Herbs": "Kräuter",
        "Spices": "Gewürze",
        "Cooking Utensils": "Kochutensilien",
        "Kitchen Appliances": "Küchengeräte",
        "Furniture": "Möbel",
        "Architectural Styles": "Architekturstile",
        "World Leaders": "Weltführer",
        "Historical Battles": "Historische Schlachten",
        "Wars": "Kriege",
        "Sports Equipment": "Sportausrüstung",
        "Olympic Sports": "Olympische Sportarten",
        "Card Games": "Kartenspiele",
        "Puzzles": "Puzzles",
        "Programming Languages": "Programmiersprachen",
        "Operating Systems": "Betriebssysteme",
        "Tech Companies": "Technologieunternehmen",
        "Inventions": "Erfindungen",
        "Natural Disasters": "Naturkatastrophen",
        "Weather Phenomena": "Wetterphänomene",
        "Sea Creatures": "Meereskreaturen",
        "Mountain Ranges": "Gebirgsketten",
        "Deserts": "Wüsten",
        "Islands": "Inseln",
        "National Parks": "Nationalparks",
        "Dog Breeds": "Hunderassen",
        "Cat Breeds": "Katzenrassen",
        "Horse Breeds": "Pferderassen",
        "Bird Species": "Vogelarten"
    },
    "Dutch": {
        "Animals": "Dieren",
        "Cities": "Steden",
        "Countries": "Landen",
        "Famous People": "Beroemde Personen",
        "Food": "Voedsel",
        "Movies": "Films",
        "Occupations": "Beroepen",
        "Sports": "Sporten",
        "Historical Events": "Historische Gebeurtenissen",
        "Books": "Boeken",
        "Instruments": "Instrumenten",
        "Plants": "Planten",
        "Toys": "Speelgoed",
        "Brands": "Merken",
        "Celebrities": "Bekendheden",
        "Rivers": "Rivieren",
        "Mountains": "Bergen",
        "Historical Figures": "Historische Figuren",
        "TV Shows": "Televisieprogramma's",
        "Musical Instruments": "Muziekinstrumenten",
        "Actors": "Acteurs",
        "Colors": "Kleuren",
        "Diseases": "Ziekten",
        "School Subjects": "Schoolvakken",
        "Video Games": "Videospellen",
        "Authors": "Auteurs",
        "Board Games": "Bordspellen",
        "Car Brands": "Automerken",
        "Fruits": "Fruit",
        "Vegetables": "Groenten",
        "Scientists": "Wetenschappers",
        "Sports Personalities": "Sportpersoonlijkheden",
        "Computer Parts": "Computeronderdelen",
        "Languages": "Talen",
        "Beaches": "Stranden",
        "Historical Monuments": "Historische Monumenten",
        "Musical Genres": "Muziekgenres",
        "Dance Styles": "Dansstijlen",
        "Mythical Creatures": "Mythische Wezens",
        "Astronomical Objects": "Astronomische Objecten",
        "Chemical Elements": "Chemische Elementen",
        "Mathematical Concepts": "Wiskundige Concepten",
        "Philosophers": "Filosofen",
        "Painters": "Schilders",
        "Literary Genres": "Literaire Genres",
        "Poets": "Dichters",
        "Festivals": "Festivals",
        "Religions": "Religies",
        "Political Ideologies": "Politieke Ideologieën",
        "Mammals": "Zoogdieren",
        "Birds": "Vogels",
        "Fish": "Vissen",
        "Reptiles": "Reptielen",
        "Amphibians": "Amfibieën",
        "Trees": "Bomen",
        "Flowers": "Bloemen",
        "Herbs": "Kruiden",
        "Spices": "Specerijen",
        "Cooking Utensils": "Kookgerei",
        "Kitchen Appliances": "Keukenapparatuur",
        "Furniture": "Meubels",
        "Architectural Styles": "Architectuurstijlen",
        "World Leaders": "Wereldleiders",
        "Historical Battles": "Historische Veldslagen",
        "Wars": "Oorlogen",
        "Sports Equipment": "Sportuitrusting",
        "Olympic Sports": "Olympische Sporten",
        "Card Games": "Kaartspellen",
        "Puzzles": "Puzzels",
        "Programming Languages": "Programmeertalen",
        "Operating Systems": "Besturingssystemen",
        "Tech Companies": "Technologiebedrijven",
        "Inventions": "Uitvindingen",
        "Natural Disasters": "Natuurrampen",
        "Weather Phenomena": "Weerfenomenen",
        "Sea Creatures": "Zeedieren",
        "Mountain Ranges": "Bergketens",
        "Deserts": "Woestijnen",
        "Islands": "Eilanden",
        "National Parks": "Nationale Parken",
        "Dog Breeds": "Hondenrassen",
        "Cat Breeds": "Kattenrassen",
        "Horse Breeds": "Paardenrassen",
        "Bird Species": "Vogelsoorten"
    }
}

if __name__ == "__main__":
    print(len(categories))
